# Generated by Django 4.2.9 on 2024-01-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='logo',
        ),
    ]
